name: Manhattan Plugin
main: org.bvsd.manhattanplugin.ManhattanPlugin
version: 0.1
description: helps with the Manhattan bukkit server
author: DonoA
authors: [DonoA]
commands:
  WorldJump:
    description: jumps to a new world
    usage: /WorldJump <survival | creative>
  DeathGames:
    description: enter or leave the deathgames
    usage: /DeathGames <join | leave | equip>
  HZone:
    description: create or remove a hostile zone
    usage: |
           /HZone add [radius] [difficulty]
           /HZone remove
  Vanish:
    description: become invisible
    usage: /vanish
  Chest:
    description: Edit chest settings
    usage: |
           /chest friend <add|remove|list|clear> <player>
           /chest request <accept|ban>
           /chest set <private|restricted|public>
permissions:
  ManhattanPlugin.Mod:
    default: op
    description: permissions for Mods.