name: Manhattan Plugin
main: org.bvsd.manhattanplugin.mms
version: 0.1
description: helps with the Manhattan bukkit server
author: DonoA
commands:
  WorldJump:
    description: jumps to a new world
    usage: /WorldJump <survival | creative>
  DeathGames:
    description: enter or leave the deathgames
    usage: /DeathGames <join | leave>
  HZone:
    description: create or remove a hostile zone
    usage: |
           /HZone add [radius] [difficulty]
           /HZone remove
  